# scripts/load_products.py

from sqlalchemy.orm import Session
from app.models.products import Product
from app.database import SessionLocal

category_map = {
    "Dry Goods": 1,
    "General Merchandise": 2,
    "Produce Fresh": 3
}

product_entries = [
    ("Dry Goods", "Letter Cleaning"),
    ("General Merchandise", "Raise Canned Foods"),
    ("Dry Goods", "Investment Leafy Greens"),
    ("General Merchandise", "Offer Fruits"),
    ("Dry Goods", "Though Personal Care"),
    ("Dry Goods", "Seat Personal Care"),
    ("General Merchandise", "Employee Paper Products"),
    ("General Merchandise", "Great Vegetables"),
    ("Dry Goods", "Pattern Paper Products"),
    ("General Merchandise", "Town Vegetables"),
    ("Dry Goods", "Voice Personal Care"),
    ("Dry Goods", "Idea Vegetables"),
    ("Dry Goods", "Seat Personal Care"),
    ("Dry Goods", "Difference Canned Foods"),
    ("Dry Goods", "About Paper Products"),
    ("General Merchandise", "Office Cleaning"),
    ("Dry Goods", "Reality Leafy Greens"),
    ("General Merchandise", "Song Canned Foods"),
    ("Dry Goods", "Care Cleaning"),
    ("Dry Goods", "Region Cereals"),
    ("General Merchandise", "Summer Personal Care"),
    ("Dry Goods", "Country Leafy Greens"),
    ("Dry Goods", "Themselves Leafy Greens"),
    ("General Merchandise", "Themselves Cleaning"),
    ("Dry Goods", "Decide Pasta"),
    ("Dry Goods", "Training Leafy Greens"),
    ("General Merchandise", "On Canned Foods"),
    ("Dry Goods", "Everybody Pasta"),
    ("Dry Goods", "Medical Paper Products"),
    ("General Merchandise", "Theory Cleaning"),
    ("General Merchandise", "Almost Cleaning"),
    ("Dry Goods", "Stuff Fruits"),
    ("Dry Goods", "Social Personal Care"),
    ("Dry Goods", "Medical Paper Products"),
    ("Dry Goods", "Apply Vegetables"),
    ("Dry Goods", "Four Pasta"),
    ("General Merchandise", "Energy Vegetables"),
    ("General Merchandise", "Common Vegetables"),
    ("Dry Goods", "Economic Canned Foods"),
    ("General Merchandise", "Of Personal Care"),
    ("General Merchandise", "Star Leafy Greens"),
    ("Dry Goods", "Back Leafy Greens"),
    ("General Merchandise", "Bank Personal Care"),
    ("General Merchandise", "Rise Personal Care"),
    ("General Merchandise", "Chair Paper Products"),
    ("General Merchandise", "Catch Leafy Greens"),
    ("Dry Goods", "Ask Cleaning"),
    ("Dry Goods", "National Cereals"),
    ("Dry Goods", "Investment Leafy Greens"),
    ("Dry Goods", "Pattern Fruits"),
    ("General Merchandise", "Boy Cereals"),
    ("General Merchandise", "Bar Vegetables"),
    ("General Merchandise", "Join Paper Products"),
    ("Dry Goods", "While Vegetables"),
    ("Dry Goods", "Land Cereals"),
    ("General Merchandise", "Evidence Fruits"),
    ("Dry Goods", "Find Canned Foods"),
    ("General Merchandise", "Reveal Vegetables"),
    ("General Merchandise", "Determine Canned Foods"),
    ("Dry Goods", "Decision Leafy Greens"),
    ("General Merchandise", "Accept Leafy Greens"),
    ("General Merchandise", "Ready Leafy Greens"),
    ("General Merchandise", "These Canned Foods"),
    ("General Merchandise", "Claim Cleaning"),
    ("Dry Goods", "Down Vegetables"),
    ("Dry Goods", "Four Paper Products"),
    ("Dry Goods", "Able Pasta"),
    ("General Merchandise", "Five Fruits"),
    ("General Merchandise", "For Pasta"),
    ("General Merchandise", "Learn Pasta"),
    ("General Merchandise", "Available Pasta"),
    ("General Merchandise", "Simply Leafy Greens"),
    ("General Merchandise", "Family Vegetables"),
    ("Dry Goods", "First Canned Foods"),
    ("Dry Goods", "Some Paper Products"),
    ("General Merchandise", "Leader Personal Care"),
    ("General Merchandise", "Pattern Paper Products"),
    ("Dry Goods", "Skin Pasta"),
    ("General Merchandise", "Science Cleaning"),
    ("General Merchandise", "None Paper Products"),
    ("General Merchandise", "Surface Canned Foods"),
    ("Dry Goods", "Boy Vegetables"),
    ("Dry Goods", "Live Leafy Greens"),
    ("General Merchandise", "May Canned Foods"),
    ("General Merchandise", "Certainly Fruits"),
    ("Dry Goods", "Remember Canned Foods"),
    ("General Merchandise", "Authority Pasta"),
    ("General Merchandise", "Star Leafy Greens"),
    ("General Merchandise", "Turn Personal Care"),
    ("General Merchandise", "Pm Cleaning"),
    ("General Merchandise", "Agent Personal Care"),
    ("Dry Goods", "Company Cleaning"),
    ("General Merchandise", "Though Fruits"),
    ("General Merchandise", "Town Vegetables"),
    ("Dry Goods", "Assume Leafy Greens"),
    ("General Merchandise", "Bag Cereals"),
    ("General Merchandise", "Happy Pasta"),
    ("Dry Goods", "Game Cleaning"),
    ("Dry Goods", "Throw Fruits"),
    ("Dry Goods", "Make Vegetables"),
    ("Dry Goods", "Health Leafy Greens"),
    ("Dry Goods", "Different Canned Foods"),
    ("General Merchandise", "Center Canned Foods"),
    ("Dry Goods", "Professional Leafy Greens"),
    ("Dry Goods", "Nothing Canned Foods"),
    ("Dry Goods", "Artist Cereals"),
    ("General Merchandise", "Movement Leafy Greens"),
    ("Dry Goods", "Science Cleaning"),
    ("General Merchandise", "Attack Pasta"),
    ("Dry Goods", "Artist Cereals"),
    ("Dry Goods", "Soon Canned Foods"),
    ("Dry Goods", "Part Vegetables"),
    ("General Merchandise", "Health Cereals"),
    ("Dry Goods", "Compare Vegetables"),
    ("Dry Goods", "Tonight Cereals"),
    ("General Merchandise", "Lot Cereals"),
    ("General Merchandise", "Water Paper Products"),
    ("Dry Goods", "Sure Vegetables"),
    ("Dry Goods", "Present Vegetables"),
    ("General Merchandise", "Various Leafy Greens"),
    ("General Merchandise", "Election Vegetables"),
    ("General Merchandise", "Style Fruits"),
    ("General Merchandise", "Capital Personal Care"),
    ("Dry Goods", "Show Canned Foods"),
    ("Dry Goods", "Small Cereals"),
    ("Dry Goods", "Wide Vegetables"),
    ("Dry Goods", "Physical Canned Foods"),
    ("General Merchandise", "Upon Personal Care"),
    ("General Merchandise", "Fly Fruits"),
    ("General Merchandise", "Environmental Vegetables"),
    ("General Merchandise", "Protect Leafy Greens"),
    ("General Merchandise", "Could Canned Foods"),
    ("General Merchandise", "Character Canned Foods"),
    ("General Merchandise", "International Canned Foods"),
    ("General Merchandise", "Question Pasta"),
    ("General Merchandise", "Of Personal Care"),
    ("General Merchandise", "Science Cleaning"),
    ("General Merchandise", "Least Canned Foods"),
    ("General Merchandise", "Again Cereals"),
    ("Dry Goods", "Win Cleaning"),
    ("Dry Goods", "Evidence Leafy Greens"),
    ("Dry Goods", "Public Cleaning"),
    ("Dry Goods", "Beat Fruits"),
    ("Dry Goods", "Company Fruits"),
    ("Dry Goods", "Mention Cereals"),
    ("Dry Goods", "Improve Personal Care"),
    ("Dry Goods", "List Cleaning"),
    ("General Merchandise", "True Personal Care"),
    ("General Merchandise", "Cold Cleaning"),
    ("Dry Goods", "Reality Leafy Greens"),
    ("Dry Goods", "Reflect Canned Foods"),
    ("Dry Goods", "Least Canned Foods"),
    ("General Merchandise", "Pattern Paper Products"),
    ("General Merchandise", "Walk Personal Care"),
    ("Dry Goods", "Discuss Vegetables"),
    ("Dry Goods", "Arm Paper Products"),
    ("General Merchandise", "Least Pasta"),
    ("General Merchandise", "Position Canned Foods"),
    ("General Merchandise", "Cold Cleaning"),
    ("Dry Goods", "Thought Vegetables"),
    ("General Merchandise", "Newspaper Pasta"),
    ("General Merchandise", "Top Personal Care"),
    ("Dry Goods", "Republican Leafy Greens"),
    ("Dry Goods", "Image Paper Products"),
    ("Dry Goods", "Much Vegetables"),
    ("Dry Goods", "Look Leafy Greens"),
    ("Dry Goods", "According Leafy Greens"),
    ("Dry Goods", "Free Pasta"),
    ("General Merchandise", "Election Vegetables"),
    ("General Merchandise", "Type Cereals"),
    ("General Merchandise", "Law Cereals"),
    ("Dry Goods", "Clearly Canned Foods"),
    ("General Merchandise", "Authority Cereals"),
    ("Dry Goods", "Organization Personal Care"),
    ("General Merchandise", "Wear Paper Products"),
    ("General Merchandise", "Development Cleaning"),
    ("Dry Goods", "Boy Cereals"),
    ("General Merchandise", "Section Cleaning"),
    ("General Merchandise", "Wish Cereals"),
    ("General Merchandise", "Six Vegetables"),
    ("General Merchandise", "Only Leafy Greens"),
    ("General Merchandise", "President Paper Products"),
    ("Dry Goods", "Difficult Leafy Greens"),
    ("Dry Goods", "Theory Cleaning"),
    ("General Merchandise", "Cover Fruits"),
    ("General Merchandise", "Right Fruits"),
    ("General Merchandise", "Cover Fruits"),
    ("General Merchandise", "Apply Cereals"),
    ("Dry Goods", "Of Personal Care"),
    ("Dry Goods", "Wide Canned Foods"),
    ("Dry Goods", "Notice Leafy Greens"),
    ("General Merchandise", "Available Canned Foods"),
    ("General Merchandise", "Performance Personal Care"),
    ("Dry Goods", "Until Fruits"),
    ("General Merchandise", "Set Cereals"),
    ("General Merchandise", "News Canned Foods"),
    ("General Merchandise", "Customer Vegetables"),
    ("General Merchandise", "Loss Cleaning"),
    ("Dry Goods", "President Paper Products"),
    ("Dry Goods", "City Pasta"),
    ("Dry Goods", "Low Vegetables"),
    ("General Merchandise", "Every Cereals"),
    ("General Merchandise", "Evidence Leafy Greens"),
    ("General Merchandise", "Mouth Personal Care"),
    ("General Merchandise", "Society Leafy Greens"),
    ("Dry Goods", "Government Leafy Greens"),
    ("Dry Goods", "We Cereals"),
    ("General Merchandise", "Dark Cereals"),
    ("General Merchandise", "Part Vegetables"),
    ("General Merchandise", "Career Cleaning"),
    ("Dry Goods", "Business Canned Foods"),
    ("General Merchandise", "Ground Leafy Greens"),
    ("General Merchandise", "Hundred Canned Foods"),
    ("Dry Goods", "Evidence Leafy Greens"),
    ("General Merchandise", "On Canned Foods"),
    ("Dry Goods", "Ask Vegetables"),
    ("General Merchandise", "Question Leafy Greens"),
    ("General Merchandise", "Be Leafy Greens"),
    ("Dry Goods", "Nice Vegetables"),
    ("General Merchandise", "Be Leafy Greens"),
    ("General Merchandise", "Everyone Fruits"),
    ("General Merchandise", "Weight Vegetables"),
    ("General Merchandise", "Everybody Pasta"),
    ("General Merchandise", "Game Cleaning"),
    ("Dry Goods", "Business Canned Foods"),
    ("Dry Goods", "What Vegetables"),
    ("General Merchandise", "Reality Leafy Greens"),
    ("Dry Goods", "Common Vegetables"),
    ("Dry Goods", "Since Pasta"),
    ("Dry Goods", "Dinner Cleaning"),
    ("General Merchandise", "Until Fruits"),
    ("Dry Goods", "Pattern Paper Products"),
    ("General Merchandise", "Indeed Pasta"),
    ("Dry Goods", "Science Personal Care"),
    ("General Merchandise", "For Pasta"),
    ("General Merchandise", "Lot Cereals"),
    ("Dry Goods", "Theory Cleaning"),
    ("Dry Goods", "Many Fruits"),
    ("Dry Goods", "Wish Cereals"),
    ("General Merchandise", "Time Vegetables"),
    ("Dry Goods", "Customer Vegetables"),
    ("Dry Goods", "Threat Canned Foods"),
    ("Dry Goods", "Fund Pasta"),
    ("Dry Goods", "Participant Fruits"),
    ("Dry Goods", "May Fruits"),
    ("General Merchandise", "Health Cereals"),
    ("Dry Goods", "Individual Pasta"),
    ("General Merchandise", "These Canned Foods"),
    ("General Merchandise", "Art Cleaning"),
    ("General Merchandise", "Training Leafy Greens"),
    ("General Merchandise", "Word Canned Foods"),
    ("General Merchandise", "Move Personal Care"),
    ("General Merchandise", "Traditional Vegetables"),
    ("Dry Goods", "Past Fruits"),
    ("General Merchandise", "Worry Cleaning"),
    ("Dry Goods", "Author Leafy Greens"),
    ("General Merchandise", "Expect Canned Foods"),
    ("General Merchandise", "Past Fruits"),
    ("General Merchandise", "Theory Canned Foods"),
    ("Dry Goods", "Though Fruits"),
    ("Dry Goods", "Hour Pasta"),
    ("General Merchandise", "Nice Leafy Greens"),
    ("General Merchandise", "Wear Paper Products"),
    ("Dry Goods", "Parent Leafy Greens"),
    ("General Merchandise", "Sign Fruits"),
    ("General Merchandise", "Old Pasta"),
    ("General Merchandise", "Base Vegetables"),
    ("General Merchandise", "Someone Pasta"),
    ("General Merchandise", "Star Leafy Greens"),
    ("General Merchandise", "Cold Cleaning"),
    ("General Merchandise", "First Canned Foods"),
    ("General Merchandise", "Feel Canned Foods"),
    ("General Merchandise", "Lot Cereals"),
    ("Dry Goods", "Though Fruits"),
    ("General Merchandise", "Push Pasta"),
    ("Dry Goods", "Question Pasta"),
    ("Dry Goods", "Western Cleaning"),
    ("General Merchandise", "I Pasta"),
    ("General Merchandise", "Sure Leafy Greens"),
    ("Dry Goods", "Store Vegetables"),
    ("Dry Goods", "Safe Personal Care"),
    ("Dry Goods", "Inside Paper Products"),
    ("Dry Goods", "Rise Personal Care"),
    ("Dry Goods", "According Leafy Greens"),
    ("General Merchandise", "Common Vegetables"),
    ("Dry Goods", "We Pasta"),
    ("General Merchandise", "Simply Cereals"),
    ("General Merchandise", "Everyone Vegetables"),
    ("Dry Goods", "Four Pasta"),
    ("General Merchandise", "Amount Cereals"),
    ("General Merchandise", "Protect Leafy Greens"),
    ("General Merchandise", "Explain Cereals"),
    ("Dry Goods", "Better Cleaning"),
    ("Dry Goods", "Training Paper Products"),
    ("Dry Goods", "Second Paper Products"),
    ("General Merchandise", "After Paper Products"),
    ("Dry Goods", "Kind Pasta"),
    ("General Merchandise", "Authority Personal Care"),
    ("General Merchandise", "Least Pasta"),
    ("General Merchandise", "General Cereals")
  ]

def insert_products():
    db: Session = SessionLocal()
    try:
        for category_name, product_name in product_entries:
            category_id = category_map.get(category_name)
            if category_id:
                product = Product(product_name=product_name, category_id=category_id)
                db.add(product)
            else:
                print(f"⚠️ Unknown category: {category_name} for product: {product_name}")
        db.commit()
        print(f"✅ Inserted {len(product_entries)} products with mapped category IDs.")
    finally:
        db.close()


