from sqlalchemy import Column, Integer, String, Float, Date, Boolean
from app.database import Base

class Inventory(Base):
    __tablename__ = "inventory"
    id = Column(Integer, primary_key=True, index=True)
    sku_id = Column(String, index=True)
    product_name = Column(String)
    category = Column(String)
    store_id = Column(String, index=True)
    supplier_name = Column(String)
    received_date = Column(Date)
    expiry_date = Column(Date)
    system_quantity_received = Column(Integer)
    actual_quantity_received = Column(Integer)
    difference_system_actual = Column(Integer)
    number_damaged_units = Column(Integer)
    number_dump_units = Column(Integer)
    number_expired_units = Column(Integer)
    inventory_on_hand = Column(Integer)
    unit_sold = Column(Integer)
    days_active = Column(Integer)
    shelf_life = Column(Integer)
    sell_through_rate_per_day = Column(Float)
    sell_through_rate = Column(Float)
    shelf_life_remaining = Column(Integer)
    shelf_life_used_pct = Column(Float)
    inventory_status = Column(String)
    cost_price = Column(Float)
    selling_price = Column(Float)
    original_revenue = Column(Float)
    cogs = Column(Float)
    original_gross_margin = Column(Float)
    inventory_age_days = Column(Integer)
    is_returnable = Column(Boolean)
    is_perishable = Column(Boolean)
    region_historical = Column(String)
    markdown_pct = Column(Float)
    days_of_supply = Column(Integer)
    required_markdown_pct = Column(Float)
    predicted_upliftment_factor = Column(Float)
